# Generated by Django 5.2.10 on 2026-01-12 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='journalist',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscribed_journalists',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscribed_publishers',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'journalist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='editor_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('editor', 'Editor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
